INSERT INTO cars (id, color, number, brand)
VALUES
  (gen_random_uuid(), 'Red', 'A1234', 'Toyota'),
  (gen_random_uuid(), 'Blue', 'B1234', 'Honda'),
  (gen_random_uuid(), 'Green', 'C1234', 'Ford'),
  (gen_random_uuid(), 'Black', 'D1234', 'Chevrolet'),
  (gen_random_uuid(), 'White', 'E1234', 'BMW'),
  (gen_random_uuid(), 'Silver', 'F1234', 'Audi'),
  (gen_random_uuid(), 'Gray', 'G1234', 'Mercedes'),
  (gen_random_uuid(), 'Orange', 'H1234', 'Tesla'),
  (gen_random_uuid(), 'Yellow', 'I1234', 'Nissan'),
  (gen_random_uuid(), 'Purple', 'J1234', 'Volkswagen'),
  (gen_random_uuid(), 'Brown', 'K1234', 'Ford'),
  (gen_random_uuid(), 'Pink', 'L1234', 'Fiat'),
  (gen_random_uuid(), 'Maroon', 'M1234', 'Honda'),
  (gen_random_uuid(), 'Copper', 'N1234', 'Toyota'),
  (gen_random_uuid(), 'Beige', 'O1234', 'BMW'),
  (gen_random_uuid(), 'Turquoise', 'P1234', 'Chevrolet'),
  (gen_random_uuid(), 'Lime', 'Q1234', 'Audi'),
  (gen_random_uuid(), 'Indigo', 'R1234', 'Tesla'),
  (gen_random_uuid(), 'Teal', 'S1234', 'Volkswagen'),
  (gen_random_uuid(), 'Violet', 'T1234', 'Nissan');