services:
  drivers_postgresql_test:
    container_name: ms_drivers_pg_sql_test
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: tets
      POSTGRES_DB: drivers
    volumes:
      - drivers_psql_test:/data/postgres/test
    ports:
      - "5334:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  passengers_postgresql_test:
    container_name: ms_passengers_pg_sql_test
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: passengers
    volumes:
      - passengers_psql_test:/data/postgres/test
    ports:
      - "5333:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  rides_postgresql_test:
    container_name: ms_ride_pg_sql_test
    image: postgres
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: ride
    volumes:
      - rides_psql_test:/data/postgres/test
    ports:
      - "5335:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  mongo_db_test:
    container_name: mongo_db_test
    image: mongo
    restart: always
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://localhost/ratings
    ports:
      - "26017:27017"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
volumes:
  drivers_psql_test:
  passengers_psql_test:
  rides_psql_test:
