spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ms_passengers_pg_sql:5432/passengers}
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_URL:http://tempo:9411/api/v2/spans}