server:
  port: 8030
spring:
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5335/ride}
    username: ${DB_USERNAME:test}
    password: ${DB_PASSWORD:test}
  liquibase:
    change-log: classpath:/db/changelog/test-changelog.xml
  cloud:
    openfeign:
      client:
        config:
          geolocation-client:
            url: "https://api.openrouteservice.org"
            loggerLevel: full
          driver-service-client:
            url: "{app.urls.services.driver-service-url}/api/v1/drivers"
            loggerLevel: full
          passenger-service-client:
            url: "{app.urls.services.passenger-service-url}/api/v1/passengers"
            loggerLevel: full