spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ms_ride_pg_sql:5432/ride}

  kafka:
    bootstrap-servers: ms_kafka:9092
    producer:
      bootstrap-server: ms_kafka:9092
    consumer:
      bootstrap-servers: ms_kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_URL:http://tempo:9411/api/v2/spans}
