app:
  urls:
    services:
      passenger-service-url: "localhost:8010/api/v1/passengers"
      driver-service-url: "localhost:8020/api/v1/drivers"
      ride-service-url: "localhost:8030/api/v1/rides"
  rating:
    number_to_evaluate: 10
server:
  port: 8040
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: ratings
      uri: mongodb://localhost:27017/ratings
  cloud:
    openfeign:
      client:
        config:
          passenger-service-client-test:
            url: "http://localhost:9090/api/v1/passengers"
            loggerLevel: full
          driver-service-client-test:
            url: "http://localhost:9090/api/v1/drivers"
            loggerLevel: full
          ride-service-client-test:
            url: "http://localhost:9090/api/v1/rides"
            loggerLevel: full