spring:
  cloud:
    openfeign:
      client:
        config:
          passenger-service-client:
            url: "http://localhost:9090/api/v1/passengers"
            loggerLevel: full
          driver-service-client:
            url: "http://localhost:9090/api/v1/drivers"
            loggerLevel: full
          ride-service-client:
            url: "http://localhost:9090/api/v1/rides"
            loggerLevel: full