spring:
  cloud:
    openfeign:
      client:
        config:
          passenger-service-client:
            url: "{app.urls.services.passenger-service-url}/api/v1/passengers"
            loggerLevel: full
          driver-service-client:
            url: "{app.urls.services.driver-service-url}/api/v1/drivers"
            loggerLevel: full
          ride-service-client:
            url: "{app.urls.services.ride-service-url}/api/v1/rides"
            loggerLevel: full