app:
  urls:
    services:
      passenger-service-url: "passenger-service"
      driver-service-url: "driver-service"
      ride-service-url: "ride-service"
  rating:
    number_to_evaluate: 10
server:
  port: 8040

spring:
  profiles:
    active: dev
  application:
    name: rating-service
  data:
    mongodb:
      port: 27017
      host: localhost
      database: ratings
      uri: mongodb://localhost:27017/ratings

