app:
  rating:
    number_to_evaluate: 10
  urls:
    services:
      ride-service-url: "localhost:8030/api/v1/rides"
server:
  port: 8040
spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: ratings
      uri: mongodb://localhost:27017/ratings
  cloud:
    openfeign:
      client:
        config:
          ride-service-client:
            url: "http://localhost:8030/api/v1/rides"
            loggerLevel: full