spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://pg_sql_keycloak:5432/keycloak_db}
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_URL:http://tempo:9411/api/v2/spans}
keycloak:
  domain: keycloak-ms