services:
  driver-service:
    container_name: ms_drivers
    build:
      context: ../services/driver-service
      dockerfile: ../../docker/Dockerfile
      args:
        SERVICE_NAME: driver-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    ports:
      - "9020:9020"
    depends_on:
      - drivers_postgresql
    networks:
      - microservices-net

  drivers_postgresql:
    container_name: ms_drivers_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drivers
    volumes:
      - drivers_psql:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - microservices-net
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge
volumes:
  drivers_psql: