server:
  port: 8222
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: passenger-service
          uri: lb:http://PASSENGER-SERVICE
          predicates:
            - Path=/api/v1/passengers/**
        - id: ride-service
          uri: lb:http://RIDE-SERVICE
          predicates:
            - Path=/api/v1/rides/**
        - id: driver-service
          uri: lb:http://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**
        - id: rating-service
          uri: lb:http://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: gateway-service
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0