server:
  port: 8222
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: passenger-service
#          uri: lb:http://PASSENGER-SERVICE
#          predicates:
#            - Path=/api/v1/passengers/**
        - id: ride-service
          uri: lb:http://RIDE-SERVICE
          predicates:
            - Path=/api/v1/rides/**
        - id: driver-service
          uri: lb:http://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**
        - id: rating-service
          uri: lb:http://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Passenger Service
      url: /aggregate/passenger-service/v3/api-docs
    urls[1]:
      name: Driver Service
      url: /aggregate/driver-service/v3/api-docs
    urls[2]:
      name: Ride Service
      url: /aggregate/ride-service/v3/api-docs
  api-docs:
    path: /api-docs


#Actuator endpoints
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

  #Resilience4J Retry Properties
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: api-gateway
  tracing:
    sampling:
      probability: 1.0
#Res properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
        #retry
        retry:
          configs:
            default:
              max-attempts: 3
              wait-duration: 2s

  #timeouts
  timelimiter:
    configs:
      default:
        timeout-duration: 3s