server:
  port: 8222
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: passenger-service
          uri: lb:http://PASSENGER-SERVICE
          predicates:
            - Path=/api/v1/passengers/**
        - id: ride-service
          uri: lb:http://RIDE-SERVICE
          predicates:
            - Path=/api/v1/rides/**
        - id: driver-service
          uri: lb:http://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**
        - id: rating-service
          uri: lb:http://RATING-SERVICE
          predicates:
            - Path=/api/v1/ratings/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls[0]:
      name: Passenger Service
      url: /aggregate/passenger-service/v3/api-docs
    urls[1]:
      name: Driver Service
      url: /aggregate/driver-service/v3/api-docs
    urls[2]:
      name: Ride Service
      url: /aggregate/ride-service/v3/api-docs
  api-docs:
    path: /api-docs