server:
  port: 8020
spring:
  application:
    name: driver-service
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL:jdbc:postgresql://localhost:5434/drivers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:/db/changelog/app-changelog.xml

  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: lb://DRIVER-SERVICE
          predicates:
            - Path=/api/v1/drivers/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "Driver Service"
        url: /v3/api-docs
  api-docs:
    path: /v3/api-docs
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
